# Generated by Django 4.2.1 on 2023-06-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bemor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('sharif', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('pasport_seriya', models.CharField(blank=True, max_length=10, null=True)),
                ('manzil', models.CharField(max_length=150)),
                ('balans', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Joylashtirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelish_sanasi', models.DateField()),
                ('ketish_sanasi', models.DateField(blank=True, null=True)),
                ('qarovchi', models.BooleanField(default=False)),
                ('yotgan_kun_soni', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bemor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.bemor')),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveBigIntegerField()),
                ('sana', models.DateField(auto_now_add=True)),
                ('turi', models.CharField(blank=True, choices=[('Naqd', 'Naqd'), ('Plastik', 'Plastik')], max_length=50)),
                ('tolandi', models.BooleanField(default=False)),
                ('xulosa_holati', models.CharField(blank=True, choices=[('Topshirilyapti', 'Topshirilyapti'), ('Kutyapti', 'Kutyapti'), ('Kiritildi', 'Kiritildi')], max_length=30, null=True)),
                ('bemor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.bemor')),
                ('joylashtirish_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.joylashtirish')),
            ],
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qavat', models.PositiveSmallIntegerField()),
                ('raqami', models.PositiveSmallIntegerField()),
                ('xona_sigimi', models.PositiveSmallIntegerField()),
                ('bosh_joy_soni', models.PositiveSmallIntegerField()),
                ('turi', models.CharField(choices=[('Lux', 'Lux'), ('Odatiy', 'Odatiy'), ('Pol-lux', 'Pol-lux')], max_length=20)),
                ('joy_narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='XulosaShablon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xulosa_name', models.TextField()),
                ('text_xulosa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Yollanma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('narx', models.IntegerField()),
                ('qayerga', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Xulosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xulosa_matni', models.TextField()),
                ('sana', models.DateField(auto_now_add=True)),
                ('tolov_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.tolov')),
            ],
        ),
        migrations.AddField(
            model_name='tolov',
            name='yollanma_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.yollanma'),
        ),
        migrations.AddField(
            model_name='joylashtirish',
            name='xona_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.xona'),
        ),
    ]
