# Generated by Django 4.2.1 on 2023-06-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_tolov_joylashtirish_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemor',
            name='royhatdan_otgan_sana',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tolov',
            name='ozgartirilgan_sana',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
