# Generated by Django 4.2.1 on 2023-06-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_bemor_royhatdan_otgan_sana_tolov_ozgartirilgan_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemor',
            name='joylashgan',
            field=models.BooleanField(default=False),
        ),
    ]
