# Generated by Django 4.2.1 on 2023-06-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_bemor_joylashgan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov',
            name='xulosa_holati',
            field=models.CharField(blank=True, choices=[('Topshirilyapti', 'Topshirilyapti'), ('Kutyapti', 'Kutyapti'), ('Kiritildi', 'Kiritildi')], default='Topshirilyapti', max_length=30, null=True),
        ),
    ]
