# Generated by Django 4.2.1 on 2023-06-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_tolov_xulosa_holati'),
    ]

    operations = [
        migrations.AddField(
            model_name='xulosa',
            name='chop_etildi',
            field=models.BooleanField(default=False),
        ),
    ]
