# Generated by Django 4.2.1 on 2023-06-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_xulosa_chop_etildi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joylashtirish',
            name='yotgan_kun_soni',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
