# Generated by Django 4.2.1 on 2023-06-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_joylashtirish_yotgan_kun_soni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tolov',
            name='ozgartirilgan_sana',
        ),
        migrations.AddField(
            model_name='tolov',
            name='tolangan_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
