# Generated by Django 4.2.1 on 2023-06-21 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_tolov_tolangan_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolov',
            name='ozgartirilgan_sana',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='yollanma',
            name='xulosa_shablon_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.xulosashablon'),
        ),
        migrations.AlterField(
            model_name='xulosashablon',
            name='text_xulosa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
