# Generated by Django 4.2.1 on 2023-06-21 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_tolov_ozgartirilgan_sana_yollanma_xulosa_shablon_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yollanma',
            name='xulosa_shablon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.xulosashablon'),
        ),
    ]
