# Generated by Django 4.2.1 on 2023-06-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_alter_yollanma_xulosa_shablon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov',
            name='ozgartirilgan_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
