# Generated by Django 4.2.1 on 2023-06-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_rename_text_xulosa_xulosashablon_footer_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TolovQaytarish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField()),
                ('sana', models.DateField(auto_now_add=True)),
                ('izoh', models.CharField(max_length=300)),
                ('tolov_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.tolov')),
            ],
        ),
    ]
