# Generated by Django 4.2.1 on 2023-06-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_tolovqaytarish'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolov',
            name='tolangan_summa',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
