# Generated by Django 4.2.1 on 2023-08-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_alter_tolov_yollanma_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemor',
            name='tugilgan_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
