# Generated by Django 4.2.1 on 2023-08-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_alter_bemor_options_remove_bemor_pasport_seriya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolov',
            name='izoh',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tolov',
            name='tolov_qaytarildi',
            field=models.BooleanField(default=False),
        ),
    ]
