# Generated by Django 4.2.1 on 2023-08-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_chek_tolov_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemor',
            name='sharif',
            field=models.CharField(default='Aliyev', max_length=100),
            preserve_default=False,
        ),
    ]
