# Generated by Django 4.2.1 on 2023-08-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_yollanma_narx'),
    ]

    operations = [
        migrations.AddField(
            model_name='chek',
            name='vaqt',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joylashtirish',
            name='kelish_vaqti',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joylashtirish',
            name='ketish_vaqti',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
