# Generated by Django 4.2.1 on 2023-09-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0032_chek_chek_raqami_alter_subyollanma_yollanma_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chek',
            name='chek_raqami',
        ),
        migrations.AddField(
            model_name='tolov',
            name='chegirma',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tolov',
            name='subyollanma_idlar',
            field=models.ManyToManyField(blank=True, null=True, to='register.subyollanma'),
        ),
    ]
