# Generated by Django 4.2.1 on 2023-09-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0033_remove_chek_chek_raqami_tolov_chegirma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chek',
            name='chek_raqami',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
